import { Timestamp } from "firebase-admin/firestore";

/**
 * Shopping cart model
 *
 * Represents a user's cart information.
 *
 * Fields:
 * - id: Cart unique identifier (optional, usually generated by database)
 * - userId: ID of the user who owns the cart
 * - createdAt: Timestamp when the cart was created
 */
export interface Cart {
    id?: string;
    userId: string;
    createdAt: Timestamp;
}