import { Timestamp } from "firebase-admin/firestore";

/**
 * Cart item model
 *
 * Represents a single product item inside a shopping cart.
 *
 * Fields:
 * - id: Unique identifier for the cart item (optional, generated by database)
 * - cartId: ID of the cart this item belongs to
 * - productId: ID of the product added to the cart
 * - quantity: Number of units of the product in the cart
 * - createdAt: Timestamp when the item was added to the cart
 */
export interface CartItem {
    id?: string;
    cartId: string;
    productId: string;
    quantity: number;
    createdAt: Timestamp;
}